#ifndef IC_DEFINES
#define IC_DEFINES

#define ALL_OK 0b0

// Ошибки чтения BMP
#define IC_BMP_ERROR_NULL_FILENAME 0b0011
#define IC_BMP_ERROR_OPENING_FILE 0b0101
#define IC_BMP_ERROR_INVALID_SIGNATURE 0b0111
#define IC_BMP_ERROR_INVALID_DIB 0b1001
#define IC_BMP_ERROR_INVALID_BPP 0b1011

// Сообщения о сообщениях об ошибках
#define IC_MESSAGE_BMP_ERROR_NULL_FILENAME "IC_BMP_ERROR_NULL_FILENAME"
#define IC_MESSAGE_BMP_ERROR_OPENING_FILE "IC_BMP_ERROR_OPENING_FILE"
#define IC_MESSAGE_BMP_ERROR_INVALID_SIGNATURE "IC_BMP_ERROR_INVALID_SIGNATURE"
#define IC_MESSAGE_BMP_ERROR_INVALID_DIB "IC_BMP_ERROR_INVALID_DIB"
#define IC_MESSAGE_BMP_ERROR_INVALID_BPP "IC_BMP_ERROR_INVALID_BPP"

#endif // !IC_DEFINES
#define IC_DEFINES
